FROM python:3.13-alpine

RUN apk update && apk add curl

WORKDIR /app
COPY ./sim-data/work_ui_import.sh ./work_ui_import.sh
# RUN chmod +x /app/work_ui_import.sh
COPY ./sim-data/Pulser_Minimal_Data.xlsx ./Pulser_Minimal_Data.xlsx

USER root
WORKDIR /app
CMD cd /app && cat /app/work_ui_import.sh && ./work_ui_import.sh
